// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RoutePlanner_PlanRoute_FullMethodName = "/routeplanner.RoutePlanner/PlanRoute"
)

// RoutePlannerClient is the client API for RoutePlanner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition
type RoutePlannerClient interface {
	PlanRoute(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error)
}

type routePlannerClient struct {
	cc grpc.ClientConnInterface
}

func NewRoutePlannerClient(cc grpc.ClientConnInterface) RoutePlannerClient {
	return &routePlannerClient{cc}
}

func (c *routePlannerClient) PlanRoute(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteResponse)
	err := c.cc.Invoke(ctx, RoutePlanner_PlanRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoutePlannerServer is the server API for RoutePlanner service.
// All implementations must embed UnimplementedRoutePlannerServer
// for forward compatibility.
//
// Service definition
type RoutePlannerServer interface {
	PlanRoute(context.Context, *RouteRequest) (*RouteResponse, error)
	mustEmbedUnimplementedRoutePlannerServer()
}

// UnimplementedRoutePlannerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRoutePlannerServer struct{}

func (UnimplementedRoutePlannerServer) PlanRoute(context.Context, *RouteRequest) (*RouteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlanRoute not implemented")
}
func (UnimplementedRoutePlannerServer) mustEmbedUnimplementedRoutePlannerServer() {}
func (UnimplementedRoutePlannerServer) testEmbeddedByValue()                      {}

// UnsafeRoutePlannerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoutePlannerServer will
// result in compilation errors.
type UnsafeRoutePlannerServer interface {
	mustEmbedUnimplementedRoutePlannerServer()
}

func RegisterRoutePlannerServer(s grpc.ServiceRegistrar, srv RoutePlannerServer) {
	// If the following call pancis, it indicates UnimplementedRoutePlannerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RoutePlanner_ServiceDesc, srv)
}

func _RoutePlanner_PlanRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutePlannerServer).PlanRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RoutePlanner_PlanRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutePlannerServer).PlanRoute(ctx, req.(*RouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RoutePlanner_ServiceDesc is the grpc.ServiceDesc for RoutePlanner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RoutePlanner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "routeplanner.RoutePlanner",
	HandlerType: (*RoutePlannerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlanRoute",
			Handler:    _RoutePlanner_PlanRoute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/service.proto",
}
