global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'routify-api'
    static_configs:
      - targets: ['routify-api:50051']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
